services:
  - type: web
    name: testtime-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run prisma:generate:pg && npm run prisma:push:pg && npm run prisma:seed && npm run build
    startCommand: node dist/src/main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testtime-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 7d
      - key: CORS_ORIGINS
        value: http://localhost:3000
      - key: PORT
        value: 4000

databases:
  - name: testtime-db
    plan: free
