import type { LucideIcon } from 'lucide-react';
import {
  BadgeCheck,
  Landmark,
  GraduationCap,
  Scale,
  TrainFront,
  Settings2,
  ShieldCheck,
  Building2,
  Siren,
  Umbrella,
  Users,
} from 'lucide-react';
import { ExamCategory } from './examCategories';

export interface ExamMenuCategory extends Omit<ExamCategory, 'icon'> {
  menuIcon: LucideIcon;
  examCount: number;
  exams: { name: string; slug: string; icon: string; description: string }[];
}

export const examMenuCategories: ExamMenuCategory[] = [
  {
    id: 'opsc',
    slug: 'opsc',
    name: 'OPSC',
    shortName: 'OPSC',
    fullName: 'Odisha Public Service Commission',
    description:
      'Complete preparation for OPSC Civil Services (OCS), ASO, Forest Service and other gazetted officer posts with notes, PYQs and test series.',
    color: '#2563eb',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-blue-500',
    examCount: 6,
    menuIcon: Scale,
    stats: [
      { label: 'Notes', value: '80+' },
      { label: 'Questions', value: '6,800+' },
      { label: 'Tests', value: '42+' },
      { label: 'Updates', value: '180+' },
    ],
    highlights: ['Odisha Civil Services (OCS)', 'Assistant Section Officer (ASO)', 'Odisha Forest Service', 'Gazetted Officer Posts'],
    exams: [
      { name: 'OCS', slug: 'opsc-ocs', icon: '⚖️', description: 'Odisha Civil Services' },
      { name: 'ASO', slug: 'opsc-aso', icon: '📑', description: 'Assistant Section Officer' },
      { name: 'Medical Officer', slug: 'opsc-mo', icon: '🩺', description: 'Medical Officer Recruitment' },
      { name: 'Odisha Forest Service', slug: 'opsc-ofs', icon: '🌲', description: 'Odisha Forest Service' },
      { name: 'Odisha Police Service', slug: 'opsc-ops', icon: '👮', description: 'Odisha Police Service' },
      { name: 'Other OPSC Exams', slug: 'opsc-other', icon: '📁', description: 'Other OPSC examinations' },
    ],
  },
  {
    id: 'ossc',
    slug: 'ossc',
    name: 'OSSC',
    shortName: 'OSSC',
    fullName: 'Odisha Staff Selection Commission',
    description:
      'Crack OSSC CGL, CHSL, Junior Assistant and other Group B/C posts with exam-specific mock tests, notes and previous year papers.',
    color: '#4338ca',
    gradientFrom: 'from-indigo-600',
    gradientTo: 'to-indigo-500',
    examCount: 8,
    menuIcon: BadgeCheck,
    stats: [
      { label: 'Notes', value: '45+' },
      { label: 'Questions', value: '3,200+' },
      { label: 'Tests', value: '28+' },
      { label: 'Updates', value: '150+' },
    ],
    highlights: ['Combined Graduate Level (CGL)', 'Combined Higher Secondary (CHSL)', 'Junior Assistant (JA)', 'Combined Recruitment Exam'],
    exams: [
      { name: 'CGL', slug: 'ossc-cgl', icon: '🎯', description: 'Combined Graduate Level' },
      { name: 'CHSL', slug: 'ossc-chsl', icon: '📋', description: 'Combined Higher Secondary Level' },
      { name: 'Junior Assistant', slug: 'ossc-ja', icon: '📝', description: 'Junior Assistant Recruitment' },
      { name: 'Combined Recruitment', slug: 'ossc-cre', icon: '📊', description: 'Combined Recruitment Examination' },
      { name: 'Statistical Field Surveyor', slug: 'ossc-sfs', icon: '📐', description: 'Statistical Field Surveyor' },
      { name: 'Combined Technical Exam', slug: 'ossc-cte', icon: '⚙️', description: 'Combined Technical & Non-Technical' },
      { name: 'Excise Constable', slug: 'ossc-excise', icon: '🛡️', description: 'Excise Constable Recruitment' },
      { name: 'Other OSSC Exams', slug: 'ossc-other', icon: '📁', description: 'Other OSSC examinations' },
    ],
  },
  {
    id: 'osssc',
    slug: 'osssc',
    name: 'OSSSC',
    shortName: 'OSSSC',
    fullName: 'Odisha Sub-Ordinate Staff Selection Commission',
    description:
      'Prepare for OSSSC RI, ARI, Amin, PEO, Junior Clerk and other Class-III/IV posts with targeted notes and mock test series.',
    color: '#059669',
    gradientFrom: 'from-emerald-600',
    gradientTo: 'to-emerald-500',
    examCount: 7,
    menuIcon: Users,
    stats: [
      { label: 'Notes', value: '60+' },
      { label: 'Questions', value: '4,500+' },
      { label: 'Tests', value: '35+' },
      { label: 'Updates', value: '200+' },
    ],
    highlights: ['Revenue Inspector (RI)', 'Panchayat Executive Officer (PEO)', 'Junior Clerk & Assistant', 'Amin & Class-III Posts'],
    exams: [
      { name: 'RI', slug: 'osssc-ri', icon: '🏛️', description: 'Revenue Inspector' },
      { name: 'ARI', slug: 'osssc-ari', icon: '📐', description: 'Assistant Revenue Inspector' },
      { name: 'Amin', slug: 'osssc-amin', icon: '📏', description: 'Amin Recruitment' },
      { name: 'ICDS Supervisor', slug: 'osssc-icds', icon: '👩‍🏫', description: 'ICDS Supervisor' },
      { name: 'Panchayat Executive Officer', slug: 'osssc-peo', icon: '📋', description: 'Panchayat Executive Officer' },
      { name: 'Junior Clerk', slug: 'osssc-clerk', icon: '📑', description: 'Junior Clerk Recruitment' },
      { name: 'Other OSSSC Exams', slug: 'osssc-other', icon: '📁', description: 'Other OSSSC examinations' },
    ],
  },
  {
    id: 'ssb',
    slug: 'ssb',
    name: 'SSB',
    shortName: 'SSB',
    fullName: 'Odisha State Selection Board',
    description:
      'Ace SSB Odisha Lecturer, Junior Lecturer, TGT and PGT recruitment exams with pedagogy notes and practice tests.',
    color: '#7c3aed',
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-purple-500',
    examCount: 5,
    menuIcon: GraduationCap,
    stats: [
      { label: 'Notes', value: '55+' },
      { label: 'Questions', value: '3,800+' },
      { label: 'Tests', value: '30+' },
      { label: 'Updates', value: '120+' },
    ],
    highlights: ['Lecturer Recruitment', 'Junior Lecturer', 'TGT Recruitment', 'PGT Recruitment'],
    exams: [
      { name: 'Lecturer', slug: 'ssb-lecturer', icon: '👨‍🏫', description: 'College Lecturer Recruitment' },
      { name: 'Junior Lecturer', slug: 'ssb-jl', icon: '📚', description: 'Junior Lecturer' },
      { name: 'TGT Recruitment', slug: 'ssb-tgt', icon: '📖', description: 'Trained Graduate Teacher' },
      { name: 'PGT Recruitment', slug: 'ssb-pgt', icon: '🧑‍🏫', description: 'Post Graduate Teacher' },
      { name: 'Other SSB Exams', slug: 'ssb-other', icon: '📁', description: 'Other SSB examinations' },
    ],
  },
  {
    id: 'odisha-police',
    slug: 'odisha-police',
    name: 'Odisha Police',
    shortName: 'Police',
    fullName: 'Odisha Police Recruitment Exams',
    description:
      'Complete preparation for Odisha Police Constable, SI, ASI, Sepoy and Fireman recruitment with law, GK and physical aptitude practice.',
    color: '#dc2626',
    gradientFrom: 'from-red-600',
    gradientTo: 'to-red-500',
    examCount: 6,
    menuIcon: Siren,
    stats: [
      { label: 'Notes', value: '40+' },
      { label: 'Questions', value: '3,000+' },
      { label: 'Tests', value: '25+' },
      { label: 'Updates', value: '130+' },
    ],
    highlights: ['Police Constable', 'Sub-Inspector (SI)', 'ASI & Sepoy', 'Fireman Recruitment'],
    exams: [
      { name: 'Police Constable', slug: 'odisha-constable', icon: '👮', description: 'Odisha Police Constable' },
      { name: 'Sub-Inspector', slug: 'odisha-si', icon: '🕵️', description: 'Police Sub-Inspector' },
      { name: 'ASI', slug: 'odisha-asi', icon: '📋', description: 'Assistant Sub-Inspector' },
      { name: 'Sepoy', slug: 'odisha-sepoy', icon: '🛡️', description: 'Police Sepoy Recruitment' },
      { name: 'Fireman', slug: 'odisha-fireman', icon: '🔥', description: 'Odisha Fireman Recruitment' },
      { name: 'Other Police Exams', slug: 'odisha-police-other', icon: '📁', description: 'Other police exams' },
    ],
  },
  {
    id: 'ssc',
    slug: 'ssc-exams',
    name: 'SSC Exams',
    shortName: 'SSC',
    fullName: 'Staff Selection Commission',
    description:
      'Complete preparation for SSC CGL, CHSL, MTS, GD and other Staff Selection Commission exams with mock tests, notes and PYQs.',
    color: '#0d9488',
    gradientFrom: 'from-teal-600',
    gradientTo: 'to-teal-500',
    examCount: 8,
    menuIcon: BadgeCheck,
    stats: [
      { label: 'Notes', value: '120+' },
      { label: 'Questions', value: '9,500+' },
      { label: 'Tests', value: '60+' },
      { label: 'Updates', value: '250+' },
    ],
    highlights: ['SSC CGL Exam', 'SSC CHSL Exam', 'SSC MTS Exam', 'SSC GD Constable'],
    exams: [
      { name: 'SSC CGL', slug: 'ssc-cgl', icon: '🎯', description: 'Combined Graduate Level' },
      { name: 'SSC CHSL', slug: 'ssc-chsl', icon: '📋', description: 'Combined Higher Secondary Level' },
      { name: 'SSC MTS', slug: 'ssc-mts', icon: '📝', description: 'Multi Tasking Staff' },
      { name: 'SSC GD Constable', slug: 'ssc-gd', icon: '🛡️', description: 'General Duty Constable' },
      { name: 'SSC JE', slug: 'ssc-je', icon: '⚙️', description: 'Junior Engineer' },
      { name: 'SSC CPO', slug: 'ssc-cpo', icon: '👮', description: 'Central Police Organisation' },
      { name: 'SSC Steno', slug: 'ssc-steno', icon: '⌨️', description: 'Stenographer Grade C & D' },
      { name: 'SSC Selection Post', slug: 'ssc-selection-post', icon: '📁', description: 'Selection Post Phase XII' },
    ],
  },
  {
    id: 'banking',
    slug: 'banking-exams',
    name: 'Banking Exams',
    shortName: 'Banking',
    fullName: 'Bank & Insurance Recruitment Exams',
    description:
      'Prepare for IBPS PO, Clerk, SBI, RBI and other banking exams with section-wise tests and comprehensive study material.',
    color: '#2563eb',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-blue-500',
    examCount: 8,
    menuIcon: Landmark,
    stats: [
      { label: 'Notes', value: '110+' },
      { label: 'Questions', value: '10,000+' },
      { label: 'Tests', value: '70+' },
      { label: 'Updates', value: '220+' },
    ],
    highlights: ['IBPS PO & Clerk', 'SBI PO & Clerk', 'RBI Assistant', 'IBPS RRB Exams'],
    exams: [
      { name: 'IBPS PO', slug: 'ibps-po', icon: '🏦', description: 'Probationary Officer' },
      { name: 'IBPS Clerk', slug: 'ibps-clerk', icon: '🧾', description: 'Clerical Cadre' },
      { name: 'SBI PO', slug: 'sbi-po', icon: '💼', description: 'State Bank Probationary Officer' },
      { name: 'SBI Clerk', slug: 'sbi-clerk', icon: '📑', description: 'State Bank Clerk' },
      { name: 'RBI Assistant', slug: 'rbi-assistant', icon: '🏛️', description: 'Reserve Bank Assistant' },
      { name: 'RBI Grade B', slug: 'rbi-grade-b', icon: '📈', description: 'RBI Grade B Officer' },
      { name: 'IBPS RRB PO', slug: 'ibps-rrb-po', icon: '🌾', description: 'Regional Rural Bank Officer' },
      { name: 'IBPS RRB Clerk', slug: 'ibps-rrb-clerk', icon: '🧮', description: 'Regional Rural Bank Clerk' },
    ],
  },
  {
    id: 'teaching',
    slug: 'teaching-exams',
    name: 'Teaching Exams',
    shortName: 'Teaching',
    fullName: 'Teaching Eligibility & Recruitment Exams',
    description:
      'Crack CTET, KVS, NVS, DSSSB and state TET exams with pedagogy notes, practice sets and mock tests.',
    color: '#7c3aed',
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-purple-500',
    examCount: 8,
    menuIcon: GraduationCap,
    stats: [
      { label: 'Notes', value: '95+' },
      { label: 'Questions', value: '7,500+' },
      { label: 'Tests', value: '55+' },
      { label: 'Updates', value: '180+' },
    ],
    highlights: ['CTET Paper 1 & 2', 'KVS TGT & PGT', 'NVS Recruitment', 'DSSSB TGT & PGT'],
    exams: [
      { name: 'CTET', slug: 'ctet', icon: '📜', description: 'Central Teacher Eligibility Test' },
      { name: 'KVS', slug: 'kvs', icon: '🏫', description: 'Kendriya Vidyalaya Sangathan' },
      { name: 'NVS', slug: 'nvs', icon: '🎓', description: 'Navodaya Vidyalaya Samiti' },
      { name: 'DSSSB', slug: 'dsssb', icon: '🏛️', description: 'Delhi Subordinate Services' },
      { name: 'UPTET', slug: 'uptet', icon: '📖', description: 'UP Teacher Eligibility Test' },
      { name: 'TGT', slug: 'tgt', icon: '👨‍🏫', description: 'Trained Graduate Teacher' },
      { name: 'PGT', slug: 'pgt', icon: '🧑‍🏫', description: 'Post Graduate Teacher' },
      { name: 'NET / SET', slug: 'net-set', icon: '📚', description: 'National & State Eligibility Test' },
    ],
  },
  {
    id: 'civil-services',
    slug: 'civil-services',
    name: 'Civil Services',
    shortName: 'Civil Services',
    fullName: 'Civil Services Examination',
    description:
      'Ace UPSC CSE and State PSC exams with in-depth GS notes, answer writing practice and full mock test series.',
    color: '#4338ca',
    gradientFrom: 'from-indigo-600',
    gradientTo: 'to-indigo-500',
    examCount: 6,
    menuIcon: Scale,
    stats: [
      { label: 'Notes', value: '140+' },
      { label: 'Questions', value: '8,000+' },
      { label: 'Tests', value: '45+' },
      { label: 'Updates', value: '160+' },
    ],
    highlights: ['UPSC CSE Prelims & Mains', 'State PSC Exams', 'CAPF Assistant Commandant', 'IAS, IPS, IFS & IRS'],
    exams: [
      { name: 'UPSC CSE', slug: 'upsc-cse', icon: '⚖️', description: 'Civil Services Examination' },
      { name: 'UPSC CAPF', slug: 'upsc-capf', icon: '🛡️', description: 'Central Armed Police Forces' },
      { name: 'UPPSC', slug: 'uppsc', icon: '🏛️', description: 'Uttar Pradesh PSC' },
      { name: 'MPPSC', slug: 'mppsc', icon: '🌄', description: 'Madhya Pradesh PSC' },
      { name: 'BPSC', slug: 'bpsc', icon: '🌾', description: 'Bihar Public Service Commission' },
      { name: 'WBCS', slug: 'wbcs', icon: '🌊', description: 'West Bengal Civil Service' },
    ],
  },
  {
    id: 'railways',
    slug: 'railways-exams',
    name: 'Railways',
    shortName: 'Railways',
    fullName: 'Railway Recruitment Board',
    description:
      'Prepare for RRB NTPC, Group D, JE and ALP exams with topic-wise tests, previous papers and speed booster sets.',
    color: '#ea580c',
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-orange-500',
    examCount: 6,
    menuIcon: TrainFront,
    stats: [
      { label: 'Notes', value: '80+' },
      { label: 'Questions', value: '9,000+' },
      { label: 'Tests', value: '65+' },
      { label: 'Updates', value: '200+' },
    ],
    highlights: ['RRB NTPC', 'RRB Group D', 'RRB JE', 'RRB ALP & Technician'],
    exams: [
      { name: 'RRB NTPC', slug: 'rrb-ntpc', icon: '🚂', description: 'Non Technical Popular Categories' },
      { name: 'RRB Group D', slug: 'rrb-group-d', icon: '🛤️', description: 'Level 1 Posts' },
      { name: 'RRB JE', slug: 'rrb-je', icon: '⚙️', description: 'Junior Engineer' },
      { name: 'RRB ALP', slug: 'rrb-alp', icon: '🚄', description: 'Assistant Loco Pilot' },
      { name: 'RRB Technician', slug: 'rrb-technician', icon: '🔧', description: 'Technician Grade III' },
      { name: 'RPF Constable', slug: 'rpf-constable', icon: '🛡️', description: 'Railway Protection Force' },
    ],
  },
  {
    id: 'engineering',
    slug: 'engineering-recruitment',
    name: 'Engineering Recruitment',
    shortName: 'Engineering',
    fullName: 'Engineering & PSU Recruitment',
    description:
      'Crack SSC JE, AE and PSU recruitment exams like ISRO, BHEL, ONGC with core engineering and GK preparation.',
    color: '#0e7490',
    gradientFrom: 'from-cyan-600',
    gradientTo: 'to-cyan-500',
    examCount: 6,
    menuIcon: Settings2,
    stats: [
      { label: 'Notes', value: '70+' },
      { label: 'Questions', value: '5,000+' },
      { label: 'Tests', value: '40+' },
      { label: 'Updates', value: '120+' },
    ],
    highlights: ['SSC JE (Civil, Mech, EE)', 'State AE Exams', 'ISRO Recruitment', 'PSU Recruitment (BHEL, ONGC)'],
    exams: [
      { name: 'SSC JE', slug: 'ssc-je', icon: '🏗️', description: 'Junior Engineer (Civil/Mechanical/Electrical)' },
      { name: 'AE Exams', slug: 'ae-exams', icon: '📐', description: 'Assistant Engineer (State)' },
      { name: 'ISRO', slug: 'isro', icon: '🚀', description: 'Indian Space Research Organisation' },
      { name: 'BHEL', slug: 'bhel', icon: '🏭', description: 'Bharat Heavy Electricals' },
      { name: 'ONGC', slug: 'ongc', icon: '🛢️', description: 'Oil and Natural Gas Corporation' },
      { name: 'DRDO', slug: 'drdo', icon: '🔬', description: 'Defence Research & Development' },
    ],
  },
  {
    id: 'defence',
    slug: 'defence-exams',
    name: 'Defence',
    shortName: 'Defence',
    fullName: 'Defence & Armed Forces Exams',
    description:
      'Prepare for NDA, CDS, AFCAT and Armed Forces recruitment with GK, reasoning and military aptitude tests.',
    color: '#b91c1c',
    gradientFrom: 'from-red-600',
    gradientTo: 'to-red-500',
    examCount: 6,
    menuIcon: ShieldCheck,
    stats: [
      { label: 'Notes', value: '60+' },
      { label: 'Questions', value: '6,500+' },
      { label: 'Tests', value: '45+' },
      { label: 'Updates', value: '140+' },
    ],
    highlights: ['NDA & NA Exam', 'CDS Exam', 'AFCAT Exam', 'Indian Army, Navy & Air Force'],
    exams: [
      { name: 'NDA', slug: 'nda', icon: '🎖️', description: 'National Defence Academy' },
      { name: 'CDS', slug: 'cds', icon: '⚔️', description: 'Combined Defence Services' },
      { name: 'AFCAT', slug: 'afcat', icon: '✈️', description: 'Air Force Common Admission Test' },
      { name: 'Indian Army', slug: 'indian-army', icon: '🪖', description: 'Army Recruitment' },
      { name: 'Indian Navy', slug: 'indian-navy', icon: '⚓', description: 'Navy Recruitment' },
      { name: 'Coast Guard', slug: 'coast-guard', icon: '🚤', description: 'Indian Coast Guard' },
    ],
  },
  {
    id: 'state-govt',
    slug: 'state-govt-exams',
    name: 'State Govt.',
    shortName: 'State Govt',
    fullName: 'State Government Exams',
    description:
      'Comprehensive preparation for State PSC, state police, state TET and various state government recruitment exams.',
    color: '#15803d',
    gradientFrom: 'from-green-600',
    gradientTo: 'to-green-500',
    examCount: 6,
    menuIcon: Building2,
    stats: [
      { label: 'Notes', value: '100+' },
      { label: 'Questions', value: '8,500+' },
      { label: 'Tests', value: '60+' },
      { label: 'Updates', value: '240+' },
    ],
    highlights: ['State PSC Exams', 'State Police Recruitment', 'State TET & Teacher Exams', 'Clerical & Secretariat Exams'],
    exams: [
      { name: 'State PSC', slug: 'state-psc', icon: '🏛️', description: 'State Public Service Commission' },
      { name: 'State Police', slug: 'state-police', icon: '👮', description: 'State Police Constable & SI' },
      { name: 'State TET', slug: 'state-tet', icon: '🎓', description: 'State Teacher Eligibility Test' },
      { name: 'Secretariat', slug: 'secretariat', icon: '🏢', description: 'State Secretariat Exams' },
      { name: 'Forest Guard', slug: 'forest-guard', icon: '🌲', description: 'Forest & Wildlife Department' },
      { name: 'Excise Dept', slug: 'excise-dept', icon: '🍺', description: 'Excise Department Recruitment' },
    ],
  },
  {
    id: 'police',
    slug: 'police-exams',
    name: 'Police',
    shortName: 'Police',
    fullName: 'Police & Paramilitary Recruitment',
    description:
      'Crack Police Constable, SI, CISF, BSF and other paramilitary exams with law, GK and physical aptitude practice.',
    color: '#1d4ed8',
    gradientFrom: 'from-blue-700',
    gradientTo: 'to-blue-600',
    examCount: 6,
    menuIcon: Siren,
    stats: [
      { label: 'Notes', value: '65+' },
      { label: 'Questions', value: '7,000+' },
      { label: 'Tests', value: '50+' },
      { label: 'Updates', value: '170+' },
    ],
    highlights: ['Police Constable', 'Sub-Inspector (SI)', 'CISF, BSF & CRPF', 'ASI & Head Constable'],
    exams: [
      { name: 'Police Constable', slug: 'police-constable', icon: '🚔', description: 'State Police Constable' },
      { name: 'Sub-Inspector', slug: 'sub-inspector', icon: '🕵️', description: 'Police Sub-Inspector' },
      { name: 'ASI', slug: 'asi', icon: '📋', description: 'Assistant Sub-Inspector' },
      { name: 'CISF', slug: 'cisf', icon: '🛡️', description: 'Central Industrial Security Force' },
      { name: 'BSF', slug: 'bsf', icon: '🌍', description: 'Border Security Force' },
      { name: 'CRPF', slug: 'crpf', icon: '🏔️', description: 'Central Reserve Police Force' },
    ],
  },
  {
    id: 'insurance',
    slug: 'insurance-exams',
    name: 'Insurance',
    shortName: 'Insurance',
    fullName: 'Insurance Sector Recruitment',
    description:
      'Prepare for LIC AAO, ADO, NIACL, UIIC and other insurance sector exams with quantitative, reasoning and GA practice.',
    color: '#a16207',
    gradientFrom: 'from-yellow-600',
    gradientTo: 'to-yellow-500',
    examCount: 6,
    menuIcon: Umbrella,
    stats: [
      { label: 'Notes', value: '55+' },
      { label: 'Questions', value: '5,500+' },
      { label: 'Tests', value: '38+' },
      { label: 'Updates', value: '110+' },
    ],
    highlights: ['LIC AAO', 'LIC ADO', 'NIACL AO & Assistant', 'UIIC AO'],
    exams: [
      { name: 'LIC AAO', slug: 'lic-aao', icon: '🕯️', description: 'Life Insurance Assistant Administrative Officer' },
      { name: 'LIC ADO', slug: 'lic-ado', icon: '📋', description: 'Apprentice Development Officer' },
      { name: 'NIACL AO', slug: 'niacl-ao', icon: '🏛️', description: 'New India Assurance Officer' },
      { name: 'UIIC AO', slug: 'uiic-ao', icon: '🏢', description: 'United India Insurance Officer' },
      { name: 'NICL AO', slug: 'nicl-ao', icon: '🧾', description: 'National Insurance Company' },
      { name: 'GIC', slug: 'gic', icon: '🌂', description: 'General Insurance Corporation' },
    ],
  },
];

export function getExamMenuCategory(slug: string): ExamMenuCategory | undefined {
  return examMenuCategories.find((c) => c.slug === slug);
}
