export const mockTests = [
  { id: '1', title: 'OSSC CGL Prelims Full Mock 1', slug: 'ossc-cgl-prelims-full-mock-1', description: 'Full-length mock test covering all sections as per OSSC CGL Prelims pattern.', examId: 'ossc', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'medium', isFree: true, negativeMark: null, attempt_count: 1245, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '2', title: 'OSSC CGL Prelims Full Mock 2', slug: 'ossc-cgl-prelims-full-mock-2', description: 'Second full mock with updated question bank for OSSC CGL Prelims.', examId: 'ossc', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'hard', isFree: true, negativeMark: 0.25, attempt_count: 987, category: 'Pre-Exam', position: 2, isActive: true },
  { id: '3', title: 'OSSC CGL Mains Full Mock 1', slug: 'ossc-cgl-mains-full-mock-1', description: 'Full-length mains mock test with descriptive and objective sections.', examId: 'ossc', stage: 'Mains', test_type: 'full-mock', duration: 180, totalMarks: 300, question_count: 120, difficulty: 'hard', isFree: false, negativeMark: null, attempt_count: 654, category: 'Mains', position: 1, isActive: true },
  { id: '4', title: 'OSSC CGL Mains Full Mock 2', slug: 'ossc-cgl-mains-full-mock-2', description: 'Advanced mains mock with detailed solutions.', examId: 'ossc', stage: 'Mains', test_type: 'full-mock', duration: 180, totalMarks: 300, question_count: 120, difficulty: 'hard', isFree: false, negativeMark: 0.5, attempt_count: 432, category: 'Mains', position: 2, isActive: true },
  { id: '5', title: 'OSSC Arithmetic Sectional', slug: 'ossc-arithmetic-sectional', description: 'Sectional test focusing on Arithmetic for OSSC exams.', examId: 'ossc', stage: 'Prelims', test_type: 'sectional', duration: 30, totalMarks: 50, question_count: 25, difficulty: 'easy', isFree: true, negativeMark: null, attempt_count: 2100, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '6', title: 'OSSC Reasoning Sectional', slug: 'ossc-reasoning-sectional', description: 'Sectional test covering logical reasoning for OSSC.', examId: 'ossc', stage: 'Prelims', test_type: 'sectional', duration: 30, totalMarks: 50, question_count: 25, difficulty: 'medium', isFree: true, negativeMark: null, attempt_count: 1876, category: 'Pre-Exam', position: 2, isActive: true },
  { id: '7', title: 'OSSC Current Affairs Topic-wise', slug: 'ossc-current-affairs-topic', description: 'Topic-wise test covering current affairs for Odisha exams.', examId: 'ossc', stage: 'Prelims', test_type: 'topic-wise', duration: 20, totalMarks: 30, question_count: 15, difficulty: 'easy', isFree: true, negativeMark: null, attempt_count: 3210, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '8', title: 'OSSC CGL 2022 PYQ Test', slug: 'ossc-cgl-2022-pyq', description: 'Previous year questions from OSSC CGL 2022 exam.', examId: 'ossc', stage: 'Prelims', test_type: 'pyq-test', duration: 60, totalMarks: 100, question_count: 50, difficulty: 'medium', isFree: true, negativeMark: 0.25, attempt_count: 5432, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '9', title: 'OSSC CGL 2021 PYQ Test', slug: 'ossc-cgl-2021-pyq', description: 'Previous year questions from OSSC CGL 2021 exam.', examId: 'ossc', stage: 'Prelims', test_type: 'pyq-test', duration: 60, totalMarks: 100, question_count: 50, difficulty: 'medium', isFree: false, negativeMark: 0.25, attempt_count: 4123, category: 'Pre-Exam', position: 2, isActive: true },

  { id: '11', title: 'OSSSC Prelims Full Mock 1', slug: 'osssc-prelims-full-mock-1', description: 'Full mock for OSSSC Prelims with latest pattern.', examId: 'osssc', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'medium', isFree: true, negativeMark: 0.25, attempt_count: 876, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '12', title: 'OSSSC Mains Mock 1', slug: 'osssc-mains-mock-1', description: 'Mains mock test for OSSSC with descriptive answers.', examId: 'osssc', stage: 'Mains', test_type: 'full-mock', duration: 180, totalMarks: 300, question_count: 120, difficulty: 'hard', isFree: false, negativeMark: null, attempt_count: 543, category: 'Mains', position: 1, isActive: true },
  { id: '13', title: 'OSSSC Odia Language Sectional', slug: 'osssc-odia-sectional', description: 'Sectional test for Odia language proficiency.', examId: 'osssc', stage: 'Prelims', test_type: 'sectional', duration: 20, totalMarks: 40, question_count: 20, difficulty: 'easy', isFree: true, negativeMark: null, attempt_count: 1654, category: 'Pre-Exam', position: 1, isActive: true },

  { id: '14', title: 'OPSC Prelims GS Full Mock 1', slug: 'opsc-prelims-gs-mock-1', description: 'Full mock for OPSC Prelims General Studies.', examId: 'opsc', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'hard', isFree: false, negativeMark: 0.33, attempt_count: 1234, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '15', title: 'OPSC Prelims GS Mock 2', slug: 'opsc-prelims-gs-mock-2', description: 'Second OPSC Prelims GS mock with updated syllabus.', examId: 'opsc', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'hard', isFree: false, negativeMark: 0.33, attempt_count: 987, category: 'Pre-Exam', position: 2, isActive: true },
  { id: '16', title: 'OPSC CSAT Sectional', slug: 'opsc-csat-sectional', description: 'CSAT comprehension and reasoning sectional.', examId: 'opsc', stage: 'Prelims', test_type: 'sectional', duration: 40, totalMarks: 60, question_count: 30, difficulty: 'medium', isFree: true, negativeMark: null, attempt_count: 765, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '27', title: 'OPSC OCS Prelims GS PYQ 2023', slug: 'opsc-ocs-prelims-gs-pyq-2023', description: 'Previous year GS paper from OPSC OCS Prelims 2023.', examId: 'opsc', stage: 'Prelims', test_type: 'pyq-test', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'hard', isFree: true, negativeMark: 0.33, attempt_count: 3200, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '28', title: 'OPSC OCS Prelims GS PYQ 2022', slug: 'opsc-ocs-prelims-gs-pyq-2022', description: 'Previous year GS paper from OPSC OCS Prelims 2022.', examId: 'opsc', stage: 'Prelims', test_type: 'pyq-test', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'hard', isFree: true, negativeMark: 0.33, attempt_count: 2800, category: 'Pre-Exam', position: 2, isActive: true },
  { id: '29', title: 'OPSC OCS Mains GS Paper 1 PYQ 2022', slug: 'opsc-ocs-mains-gs1-pyq-2022', description: 'Previous year GS Paper 1 from OPSC OCS Mains 2022.', examId: 'opsc', stage: 'Mains', test_type: 'pyq-test', duration: 180, totalMarks: 250, question_count: 10, difficulty: 'hard', isFree: false, negativeMark: null, attempt_count: 1200, category: 'Mains', position: 1, isActive: true },

  { id: '17', title: 'SSB Odisha Prelims Mock', slug: 'ssb-odisha-prelims-mock', description: 'SSB Odisha teacher eligibility mock test.', examId: 'ssb', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 150, question_count: 75, difficulty: 'medium', isFree: true, negativeMark: 0.25, attempt_count: 2345, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '18', title: 'SSB Pedagogy Sectional', slug: 'ssb-pedagogy-sectional', description: 'Sectional on teaching pedagogy for SSB.', examId: 'ssb', stage: 'Prelims', test_type: 'sectional', duration: 25, totalMarks: 40, question_count: 20, difficulty: 'easy', isFree: true, negativeMark: null, attempt_count: 1800, category: 'Pre-Exam', position: 1, isActive: true },

  { id: '19', title: 'Odisha Police SI Prelims Mock', slug: 'odisha-police-si-prelims-mock', description: 'SI prelims mock with law and general knowledge sections.', examId: 'odisha-police', stage: 'Prelims', test_type: 'full-mock', duration: 90, totalMarks: 150, question_count: 100, difficulty: 'medium', isFree: true, negativeMark: 0.25, attempt_count: 3100, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '20', title: 'Odisha Police Constable Mock', slug: 'odisha-police-constable-mock', description: 'Constable recruitment mock test.', examId: 'odisha-police', stage: 'Prelims', test_type: 'full-mock', duration: 60, totalMarks: 100, question_count: 80, difficulty: 'easy', isFree: true, negativeMark: null, attempt_count: 4500, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '21', title: 'Odisha Police GK Sectional', slug: 'odisha-police-gk-sectional', description: 'General knowledge sectional for police exams.', examId: 'odisha-police', stage: 'Prelims', test_type: 'sectional', duration: 20, totalMarks: 30, question_count: 20, difficulty: 'easy', isFree: true, negativeMark: null, attempt_count: 2900, category: 'Pre-Exam', position: 1, isActive: true },

  { id: '22', title: 'Teaching Aptitude Mock', slug: 'teaching-aptitude-mock', description: 'Teaching aptitude test for Odisha teaching exams.', examId: 'odisha-teaching', stage: 'Prelims', test_type: 'full-mock', duration: 90, totalMarks: 100, question_count: 50, difficulty: 'medium', isFree: true, negativeMark: null, attempt_count: 1200, category: 'Pre-Exam', position: 1, isActive: true },

  { id: '23', title: 'Utkal University PG Entrance Mock', slug: 'utkal-university-pg-mock', description: 'PG entrance mock for Utkal University.', examId: 'odisha-universities', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 150, question_count: 75, difficulty: 'hard', isFree: false, negativeMark: 0.25, attempt_count: 456, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '24', title: 'OUAT Entrance Mock', slug: 'ouat-entrance-mock', description: 'OUAT agriculture entrance mock test.', examId: 'odisha-universities', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 150, question_count: 75, difficulty: 'medium', isFree: true, negativeMark: 0.25, attempt_count: 678, category: 'Pre-Exam', position: 1, isActive: true },

  { id: '25', title: 'ICAR ARS Prelims Mock', slug: 'icar-ars-prelims-mock', description: 'ICAR ARS prelims mock for Odisha agriculture officers.', examId: 'other', stage: 'Prelims', test_type: 'full-mock', duration: 120, totalMarks: 200, question_count: 100, difficulty: 'hard', isFree: false, negativeMark: 0.33, attempt_count: 345, category: 'Pre-Exam', position: 1, isActive: true },
  { id: '26', title: 'CTET Odisha Mock', slug: 'ctet-odisha-mock', description: 'CTET paper 1 mock for Odisha teaching aspirants.', examId: 'other', stage: 'Prelims', test_type: 'full-mock', duration: 150, totalMarks: 150, question_count: 90, difficulty: 'medium', isFree: true, negativeMark: null, attempt_count: 2100, category: 'Pre-Exam', position: 1, isActive: true },
];

export const mockQuestions = [
  { id: '1', text: 'Who was the first Chief Minister of Odisha?', options: ['Harekrushna Mahatab', 'Biju Patnaik', 'Nandini Satpathy', 'Janaki Ballabh Patnaik'], answer: 'Harekrushna Mahatab', subjectId: 'odisha-history', year: 2022, examId: 'ossc', difficulty: 'easy' },
  { id: '2', text: 'Which river is known as the "Sorrow of Odisha"?', options: ['Mahanadi', 'Brahmani', 'Baitarani', 'Rushikulya'], answer: 'Baitarani', subjectId: 'odisha-geography', year: 2022, examId: 'ossc', difficulty: 'easy' },
  { id: '3', text: 'What is the state animal of Odisha?', options: ['Tiger', 'Elephant', 'Sambar', 'Chital'], answer: 'Elephant', subjectId: 'general-knowledge', year: 2021, examId: 'ossc', difficulty: 'easy' },
];

export const mockExams = [
  { id: 'ossc', name: 'OSSC', fullName: 'Odisha Staff Selection Commission', slug: 'ossc', category: 'State-Level', description: 'OSSC conducts various recruitment exams for Group B and Group C posts.', icon: 'Building2', questionCount: 500, testCount: 200, noteCount: 80 },
  { id: 'osssc', name: 'OSSSC', fullName: 'Odisha Sub-ordinate Staff Selection Commission', slug: 'osssc', category: 'State-Level', description: 'OSSSC conducts recruitment for various subordinate posts.', icon: 'Users', questionCount: 300, testCount: 120, noteCount: 50 },
  { id: 'opsc', name: 'OPSC', fullName: 'Odisha Public Service Commission', slug: 'opsc', category: 'State-Level', description: 'OPSC conducts civil services and other gazetted posts exams.', icon: 'Shield', questionCount: 400, testCount: 80, noteCount: 60 },
  { id: 'ssb', name: 'SSB Odisha', fullName: 'Odisha School Education & Teacher Eligibility Boards', slug: 'ssb', category: 'Teaching', description: 'SSB Odisha manages teacher recruitment.', icon: 'GraduationCap', questionCount: 200, testCount: 60, noteCount: 40 },
  { id: 'odisha-police', name: 'Odisha Police', fullName: 'Odisha Police Recruitment', slug: 'odisha-police', category: 'Police & Security', description: 'Police constable, SI and other departmental exams.', icon: 'Shield', questionCount: 350, testCount: 90, noteCount: 30 },
  { id: 'odisha-teaching', name: 'Odisha Teaching', fullName: 'Odisha Teaching Recruitment', slug: 'odisha-teaching', category: 'Teaching', description: 'Teaching recruitment exams across Odisha.', icon: 'BookOpen', questionCount: 150, testCount: 40, noteCount: 35 },
  { id: 'odisha-universities', name: 'Odisha Universities', fullName: 'Odisha University Entrance Exams', slug: 'odisha-universities', category: 'University Entrance', description: 'University entrance exams in Odisha.', icon: 'University', questionCount: 100, testCount: 30, noteCount: 20 },
  { id: 'other', name: 'Other Competitive', fullName: 'Other Competitive Exams in Odisha', slug: 'other', category: 'Other', description: 'Other competitive exams relevant to Odisha.', icon: 'Award', questionCount: 80, testCount: 25, noteCount: 15 },
];
